### ISSUE TITLE
Deterministic encoding

### ISSUE THREAD

**Issue by dgl** [vshymanskyy/muon#10]
Thanks for this work. You mention a compact form in the presentation, it would be very good to define that further as a minimal deterministic encoding.

https://datatracker.ietf.org/doc/html/rfc8949#section-4.2 may be interesting if you haven't come across it.

**Comment by vshymanskyy** [comment]
Makes sense!

**Comment by vshymanskyy** [comment]
Done

**Comment by vshymanskyy** [comment]
The ticket is closed, but please feel free to provide your feedback / continue the discussion!
