### ISSUE TITLE
Are 8C tagged strings lenght encoded?

### ISSUE THREAD

**Issue by JobLeonard** [vshymanskyy/muon#12]
Given #5 it is possible for strings to contain `\u0000` values. With that in mind should I assume all 8C tags length-encoded instead of zero-terminated? Would it make sense to have a separate tag for adding zero-terminated strings and for length-encoded strings to the LRU?

**Comment by vshymanskyy** [comment]
No, `8C` tag is a separate byte that goes before any `string` value.
