### ISSUE TITLE
Request for clarification of how the 8C tag interacts with lists

### ISSUE THREAD

**Issue by JobLeonard** [vshymanskyy/muon#13]
Say I have a nested object that for some reason contains the strings "parallelepiped" and "therizinosaurus" many times, and I know this. Which of the two following ways of encoding an `8C` tagged list is correct?

    8C 90 <utf8 "parallelepiped"> 00 <utf8 "therizinosaurus"> 00 91

    90 8C  <utf8 "parallelepiped"> 00 8C <utf8 "therizinosaurus"> 00 91

~~(I'm pretending #12 doesn't exist and that 8C-tagged strings are zero-terminated, will update example once that issue is resolved)~~

My guess is that they are both correct, but the former only adds the strings to the LRU without encoding a list into the object, while the latter encodes a list of strings that also get added to the LRU. Whatever the case, it might be good to be explicit about it in the docs somewhere.

**Comment by vshymanskyy** [comment]
> My guess is that they are both correct, but the former only adds the strings to the LRU without encoding a list into the object, while the latter encodes a list of strings that also get added to the LRU. Whatever the case, it might be good to be explicit about it in the docs somewhere.

That is correct.
Overall, `8C` can be applied to any string encoding.
Even if it's an `81` string, we could specify that the string has to be moved to the top of the LRU (but i still consider this TBD)

**Comment by vshymanskyy** [comment]
Also, related to #14
