### ISSUE TITLE
Explanation of what tags actually are

### ISSUE THREAD

**Issue by axman6-da** [vshymanskyy/muon#15]
The encoding diagram has sections for both `attr` and `tags` but doesn't explain what they are or how they are encoded. Am I missing something really obvious?

I don't understand what `kv` is supposed to be, is it the same as the `dict` `kv`? What values are valid for `tag`? and `val`? several tag encodings are mentioned in the table of values, but appear to only be allowable outside of the main object?

It's not particularly clear that the encoding diagram is recursive, but does make sense once you get to the choices for lists and dicts.

**Comment by dgl** [comment]
The presentation has a slide that maybe should be in the readme too: https://docs.google.com/presentation/d/1MosK6LTy_Rr32eF6HKej6UEtf9vBzdbeSF6YPb1_e4A/present?slide=id.g13be37bd3ba_0_71
Also some notes about tags here: https://github.com/vshymanskyy/muon/tree/master/docs

**Comment by dgl** [comment]
Note attrs are not defined beyond what you see, they would be for things like CBOR tags or similar (i.e. a superset of what JSON alone can encode), see also #2 -- personally I'd be in favour of removing them until there's a good use case.

**Comment by vshymanskyy** [comment]
LMK if any further explanations are needed!
