### ISSUE TITLE
Handling of duplicate keys in dicts

### ISSUE THREAD

**Issue by axman6-da** [vshymanskyy/muon#16]
I have several questions relating to dicts:

 * What is the expected handling for dicts where the same key exists multiple times?
 * Should later values replace earlier ones? Is it implementation defined? 
 * Is there any expectation of what sort of data structure should represent a dict internally - such as an ordered key-value map, or a hash map?
 * Does/should/can the order of keys matter in an encoding?

**Comment by vshymanskyy** [comment]
I think it should be an ordered dictionary by default, (same as list, which is ordered).
It's worth adding tags for unordered dict and list (which is then treated as a set).

**Comment by vshymanskyy** [comment]
Here's the initial `Dict` specification: https://github.com/vshymanskyy/muon/blob/master/docs/README.md#dictionary
LMK your thoughts or if more details are needed.
