### ISSUE TITLE
Are `Attributes` useful enough?

### ISSUE THREAD

**Issue by vshymanskyy** [vshymanskyy/muon#2]
... or should we remove them for the sake of simplification?

alternative: move Attrubutes to Muon document level, so it can only appear in the beginning of the file or stream.

**Comment by oherych** [comment]
Personally for me not clear what reason from one additional entity. If you want to add meta information you can reuse "dict" entity for this.

**Comment by vshymanskyy** [comment]
Attributes are removed for now. In any case, they probably don't deserve a separate entity and can be implemented as a specially-tagged dict.
