### ISSUE TITLE
PSON and IOTMP libraries

### ISSUE THREAD

**Issue by georgevbsantiago** [vshymanskyy/muon#21]
Hello @vshymanskyy 

Thanks for developing the `muon `and `TinyGSM` libraries

I'm a Macker and I use Thinger.io in my projects.
They developed **PSON** (A Serialization Format for IoT Sensor Networks) and the **IOTMP** protocol.

I hope the information about `PSON `and `IOTMP `can help in `muon `development.

Thank you for your work

PSON Article: https://www.mdpi.com/1424-8220/21/13/4559/htm
PSON Github: https://github.com/thinger-io/Protoson

IOTMP Article: https://www.mdpi.com/1424-8220/19/5/1044/htm
IOTMP Github: https://github.com/thinger-io/IOTMP

Integration: `PSON `- `IOTMP `- `ARDUINO `and **`TINYGSM`** with Thinger.io
Arduino-Library: https://github.com/thinger-io/Arduino-Library

**Comment by vshymanskyy** [comment]
Thanks, will check it out
