### ISSUE TITLE
Serialization/deserialization

### ISSUE THREAD

**Issue by ertong** [vshymanskyy/muon#23]
Not sure whether this feature is a goal, but something like protobuf can provide is useful.

At the end, you build and parse messages from/to some memory objects/structs. And in would be useful to have an ability not to write serialization/deserialization code by hand, but generate it.

With possible backward compatible changes in schema in mind, generator like protobuf looks promising: you write schema, generator builds your classes/structs, for example, for microcontoller, backend and mobile app consistantly.

On the other hand, something like json serialization usually done is also a way to go.

**Comment by vshymanskyy** [comment]
this is exactly how python implementation works. it serializes/deserializes python objects
