### ISSUE TITLE
clarify self-describing

### ISSUE THREAD

**Issue by 89z** [vshymanskyy/muon#7]
Some binary formats like Protocol Buffers are not self-describing. So without a schema, you have some ambiguity of what the wire format actually represents. This is different from something like JSON, where you have full information about the data and structure of the data.

I think it would be helpful to clarify in the docs if Muon is self-describing, as personally I will not use anything like ProtoBuf, because it is not self-describing.

**Comment by vshymanskyy** [comment]
Thanks!

**Comment by 89z** [comment]
Much thanks. I wish you luck and success with your project. Good day!
