### ISSUE TITLE
Are we using signed or unsigned LEB128?

### ISSUE THREAD

**Issue by JobLeonard** [vshymanskyy/muon#9]
If I read the Python code correctly, the LEB128 lengths in strings and typed arrays are unsigned LEB128, and for the `0xBB` typed values we use signed LEB128, but it isn't specified anywhere else. Maybe that should be clarified in the images and presentation.

**Comment by vshymanskyy** [comment]
That's correct. Will be documented soon

**Comment by vshymanskyy** [comment]
Related to #8
